INSERT INTO cities (name)
VALUES ('New Kristianport'),
       ('East Gertrude'),
       ('Batzport'),
       ('West Reanna'),
       ('Maxineside'),
       ('West Lia'),
       ('East Danykaton'),
       ('New Imogene'),
       ('Koeppburgh'),
       ('New Benedictmouth'),
       ('New Dougmouth'),
       ('Stantonport'),
       ('Adamschester'),
       ('New Damariston'),
       ('Fannytown'),
       ('Sandyton'),
       ('North Ariton'),
       ('North Maximechester'),
       ('Herbertside'),
       ('Kassulkemouth'),
       ('Lake Bryana'),
       ('North Leonoraburgh'),
       ('Sengerton'),
       ('East Zander'),
       ('East Jaquanside'),
       ('West Brittanyborough'),
       ('Leathaville'),
       ('South Ashton'),
       ('Christfort'),
       ('Sporerland');