INSERT INTO cities (name)
VALUES ('Kenyattashire'),
       ('Luciostad'),
       ('Schimmelside'),
       ('Julitown'),
       ('Tremblayport'),
       ('Kuhnfurt'),
       ('Port Wallaceside'),
       ('Lake Juan'),
       ('Port Dainaport'),
       ('Santinastad'),
       ('West Rupertshire'),
       ('Sengerview'),
       ('Raynorfort'),
       ('Port Liane'),
       ('Langshire'),
       ('Jeroldton'),
       ('South Vernell'),
       ('West Sook'),
       ('Starkborough'),
       ('Huelton'),
       ('West Danburgh'),
       ('Rutherfordburgh'),
       ('Port Leahchester'),
       ('Rogahnville'),
       ('Port Brenton'),
       ('Grantberg'),
       ('Brendonfurt'),
       ('Leannonborough'),
       ('Carlosberg'),
       ('South Wendolyn'),
       ('West Annmariemouth'),
       ('Lake Alvaroburgh'),
       ('Cormierchester'),
       ('Gerlachmouth'),
       ('Tyrellbury'),
       ('Hollyberg'),
       ('New Candy'),
       ('Fritschbury'),
       ('South Normandland'),
       ('Boylebury'),
       ('East Santaville'),
       ('New Carminahaven'),
       ('Morarborough'),
       ('North Dustinport'),
       ('New Cheryl'),
       ('Port Tabithatown'),
       ('Nienowton'),
       ('Bashirianfort'),
       ('North Emmitt'),
       ('New Charlie'),
       ('East Collenefort'),
       ('Reynaldotown'),
       ('Lake Conniebury'),
       ('Pedroport'),
       ('West Demetriceville'),
       ('West Gavin'),
       ('D''Amoremouth'),
       ('Port Trudi'),
       ('South Elliotbury'),
       ('Rueckerfort'),
       ('Jorgeshire'),
       ('New Bryonfurt'),
       ('Hymanland'),
       ('Cartwrightberg'),
       ('Lake Nellburgh'),
       ('Lueilwitzmouth'),
       ('Shaynefort'),
       ('North Kentontown'),
       ('West Patricia'),
       ('Arleenport'),
       ('North Josefchester'),
       ('Cathiemouth'),
       ('North Remaburgh'),
       ('Mattview'),
       ('East Kellie'),
       ('Leifville'),
       ('East Royceburgh'),
       ('West Avelinashire'),
       ('O''Connellhaven'),
       ('Brucebury'),
       ('East Herb'),
       ('Lake Clair'),
       ('Kendahaven'),
       ('Kandichester'),
       ('Lesleyview'),
       ('Blockside'),
       ('Huelfurt'),
       ('New Lashonda'),
       ('Abbottstad'),
       ('New Cathleenborough'),
       ('Lake Lennyburgh'),
       ('Samuelstad'),
       ('Purdyhaven'),
       ('Durganhaven'),
       ('West Quentinfort'),
       ('East Chere'),
       ('South Sasha'),
       ('Toymouth'),
       ('Alberthaland'),
       ('Patrinaside'),
       ('Pacochastad'),
       ('East Maddie'),
       ('East Shannaborough'),
       ('East Cristopher'),
       ('Port Sheila'),
       ('Emanuelville'),
       ('Kingchester'),
       ('Heaneyfort'),
       ('Vanessaborough'),
       ('Torphyfurt'),
       ('New Luciusstad'),
       ('Feeneyland'),
       ('East Stewart'),
       ('Charlaborough'),
       ('North Donaldmouth'),
       ('Zachariahbury'),
       ('North Seema'),
       ('Hansenfurt'),
       ('Schinnerhaven'),
       ('West Yolandebury'),
       ('Amosside'),
       ('West Stephan'),
       ('North Annice'),
       ('New Ellenaside'),
       ('Altenwerthmouth'),
       ('Elroyberg'),
       ('South Haywood'),
       ('East Michalburgh'),
       ('Littleland'),
       ('Port Marielle'),
       ('South Warner'),
       ('Renahaven'),
       ('East Jackieview'),
       ('Stanfort'),
       ('Greenholtberg'),
       ('Morissetteshire'),
       ('East Tommie'),
       ('New Alexisburgh'),
       ('Lake Bethannberg'),
       ('East Brandon'),
       ('Kerlukefort'),
       ('Angelenaberg'),
       ('South Wallyburgh'),
       ('Cronaland'),
       ('Port Clarineland'),
       ('Hayesbury'),
       ('Stammberg'),
       ('Lake Alfred'),
       ('North Moniqueton'),
       ('New Estebanland'),
       ('Port Brantbury'),
       ('West Mayraville'),
       ('Lake Ollieville'),
       ('West Allanberg'),
       ('West Deandreside'),
       ('Towneside'),
       ('Stantonshire'),
       ('North Tristanfurt'),
       ('Nienowton'),
       ('New Lynetta'),
       ('North Sofia'),
       ('Emiliamouth'),
       ('East Ashleyport'),
       ('Marquardtburgh'),
       ('Lake Austin'),
       ('Carriebury'),
       ('Port Melbaport'),
       ('South Josephview'),
       ('Carrolmouth'),
       ('New Ryan'),
       ('Roychester'),
       ('Solberg'),
       ('Miquelfurt'),
       ('Port Roderickborough'),
       ('New Senaview'),
       ('Marlinport'),
       ('Port Dallastown'),
       ('Francoiseside'),
       ('West Ferne'),
       ('Batzberg'),
       ('East Harlanchester'),
       ('Lake Morabury'),
       ('Manteville'),
       ('East Hermelinda'),
       ('West Suzette'),
       ('Port Jodystad'),
       ('Yundtfurt'),
       ('Lindgrenville'),
       ('Merrimouth'),
       ('East Tuanview'),
       ('Cameronborough'),
       ('Georgeannahaven'),
       ('Kochland'),
       ('Port Samuelhaven'),
       ('North Ismaelton'),
       ('South Hope'),
       ('South Josueport'),
       ('North Jillian'),
       ('East Astrid'),
       ('New Emmanuelchester');