INSERT INTO countries (name, ISO, capital, continent)
VALUES ('Burkina Faso', 'IN', 'Port Randallbury', 'Uruguay'),
('Madagascar', 'JP', 'Schambergerport', 'Switzerland'),
('Algeria', 'TN', 'Beierfort', 'Guinea'),
('Hungary', 'ML', 'Port Alstad', 'Bosnia and Herzegovina'),
('Montenegro', 'ST', 'Nadiaborough', 'Algeria'),
('Chile', 'SV', 'Kubborough', 'Holy See (Vatican City State)'),
('Sudan', 'PN', 'New Irmaside', 'Pitcairn Islands'),
('Tonga', 'DJ', 'North Margeport', 'Republic of Korea'),
('Venezuela', 'NE', 'Lake Collin', 'Martinique'),
('Bulgaria', 'DZ', 'New Martin', 'Philippines'),
('Netherlands Antilles', 'JE', 'O''Connershire', 'Turkey'),
('El Salvador', 'BQ', 'West Millieland', 'Tuvalu'),
('Tunisia', 'LU', 'New Jewellfurt', 'Ghana'),
('Norfolk Island', 'CM', 'West Caitlyn', 'Mayotte'),
('Grenada', 'GW', 'Priceburgh', 'Bermuda'),
('Belgium', 'NL', 'Wildermanbury', 'American Samoa'),
('French Polynesia', 'CI', 'North Gabriellamouth', 'Cuba'),
('Wallis and Futuna', 'JE', 'Port Javon', 'Egypt'),
('Cook Islands', 'IT', 'Kaelastad', 'Swaziland'),
('Brazil', 'JP', 'Mikaylafort', 'Gambia');